In [34]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [35]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

# to suppress the warning

In [36]:
import numpy as np
import time

In [37]:
start_time = time.time()
# matrix operation here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")

0.0001


In [42]:

torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

print(f"torch-matrix-1: \n{torch_rand1}")
print(f"torch-matrix-2: \n{torch_rand2}")

print(f"np-matrix-1: \n{np_rand1}")
print(f"np-matrix-2: \n{np_rand2}")

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(rand, '\n')
print(f"Time Elapse: {elapsed_time: .8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(rand, '\n')
print(f"Time Elapse: {elapsed_time:.8f}")

torch-matrix-1: 
tensor([[0.0642, 0.0590, 0.8386,  ..., 0.0118, 0.4085, 0.8018],
        [0.3036, 0.6677, 0.2681,  ..., 0.0047, 0.1100, 0.6418],
        [0.1138, 0.0801, 0.4125,  ..., 0.4366, 0.2057, 0.0675],
        ...,
        [0.0552, 0.4877, 0.7590,  ..., 0.0276, 0.3353, 0.5933],
        [0.4009, 0.1717, 0.2892,  ..., 0.1820, 0.5961, 0.9201],
        [0.5836, 0.9140, 0.9973,  ..., 0.9694, 0.7317, 0.0429]],
       device='cuda:0')
torch-matrix-2: 
tensor([[0.4275, 0.6998, 0.7125,  ..., 0.9286, 0.5175, 0.8413],
        [0.7971, 0.6288, 0.2626,  ..., 0.7501, 0.0344, 0.9620],
        [0.4007, 0.7767, 0.8580,  ..., 0.9741, 0.8072, 0.2429],
        ...,
        [0.8175, 0.0696, 0.8103,  ..., 0.9502, 0.1846, 0.2304],
        [0.6804, 0.6768, 0.2484,  ..., 0.7927, 0.9919, 0.2091],
        [0.4051, 0.0201, 0.2580,  ..., 0.4134, 0.0084, 0.5318]],
       device='cuda:0')
np-matrix-1: 
tensor([[1.3501e-01, 8.2535e-01, 7.0959e-01,  ..., 5.3178e-02, 5.4181e-04,
         2.5687e-01],
        [7.

In [43]:
%%time

start_time = time.time()
# matrix operation here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")

0.0002
CPU times: user 0 ns, sys: 923 μs, total: 923 μs
Wall time: 595 μs


### using the time library to record execution time %%time to record the time taken for the cell to execute

In [52]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, input.T/ input.transpose, nn.linear, torch.cat, F.softmax 
# (show all the examples of functions / methods with pytorch docs)

# define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 0, 1, 1])
