In [16]:
import torch

In [17]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, torch.T / input.transpose, nn.Linear, torch.cat, F.softmax

# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1 (10% chance of getting 0, 90% chance of getting 1)
# Draw 5 samples from the multinomial distribution

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
probabilities

tensor([0.1000, 0.9000])

In [19]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0) # concatenation
out

tensor([1, 2, 3, 4, 5])

In [20]:
out = torch.tril(torch.ones(5, 5)) # triangle lower
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
out = torch.triu(torch.ones(5, 5)) # triangle upper
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [22]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [23]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [24]:
input = torch.zeros(2, 3, 4)

print(input)
out = input.transpose(0, 2)
print(out.shape)
out

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([4, 3, 2])


tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [25]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
import torch.nn as nn

In [28]:
sample = torch.tensor([10., 10., 10. ])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([9.3628, 0.3208, 1.8417], grad_fn=<SqueezeBackward4>)


In [31]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])  # [e^1, e^2, e^3] * (1/ (e^1 + e^2 + e^3))

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

In [30]:
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [54]:
int_64 = torch.randint(1, (3, 2))
print(int_64)

float_32 = torch.rand(2, 3)
print(float_32)

# Convert int_64 to float
int_64_float = int_64.float()
print(int_64_float)

# Now perform the matrix multiplication
result = torch.matmul(int_64_float, float_32)

result

tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[0.0208, 0.8236, 0.4973],
        [0.6164, 0.1644, 0.4179]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])