In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 52,  20,  23,  97,  95, -28])

In [3]:
tensor = torch.tensor([[0.1, 0.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2, 3)

In [5]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2, 3)

In [8]:
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[124324967198096, 124324967198096,     -4294967295],
        [    12884901888,              10,             145]])

In [15]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
# print(output[:, -1, :])
print(output[-1, :])


tensor([[0.3364, 0.7766, 0.1730, 0.8641, 0.1334, 0.4765, 0.2879, 0.4169, 0.7875,
         0.7830],
        [0.5849, 0.8984, 0.8832, 0.0440, 0.5878, 0.7627, 0.0816, 0.6206, 0.8622,
         0.9983],
        [0.4870, 0.1551, 0.8898, 0.5900, 0.8878, 0.7745, 0.5786, 0.3917, 0.5515,
         0.7936],
        [0.0672, 0.5360, 0.2252, 0.4289, 0.1292, 0.6597, 0.0098, 0.8413, 0.0232,
         0.5026],
        [0.7987, 0.3907, 0.5810, 0.8874, 0.7846, 0.3296, 0.5077, 0.5622, 0.9488,
         0.2472],
        [0.7450, 0.9163, 0.4973, 0.3571, 0.8972, 0.3474, 0.1272, 0.1518, 0.9931,
         0.1578],
        [0.3219, 0.4399, 0.2938, 0.4652, 0.1954, 0.7273, 0.2703, 0.8608, 0.8694,
         0.7185],
        [0.8948, 0.1022, 0.0685, 0.7957, 0.7865, 0.9666, 0.9939, 0.5573, 0.9300,
         0.8855],
        [0.4094, 0.5655, 0.0480, 0.6185, 0.2699, 0.2281, 0.7310, 0.3367, 0.7687,
         0.0953],
        [0.2066, 0.4946, 0.6909, 0.6984, 0.8955, 0.3214, 0.1153, 0.2228, 0.5389,
         0.0960],
        [0

In [23]:
x = torch.tensor([-0.85], dtype=torch.float32)
y1 = nn.ReLU()(x)
y2 = F.sigmoid(x)
print(y1)
print(y2)

tensor([0.])
tensor([0.2994])
